In [3]:
# The data consist of microarrays from 89 different individuals with acute lymphoblastic leukemia (ALL)
# There are three subgroups of the data including B-cell tumours with BRC/ABL mutation 
# and those ALL samples with no cytogenic abnormalities (NEG), 
# and ALL1/AF4 show a translocation between chromosomes 4 and 11 etc.
import numpy as np
import pandas as pd
from sklearn import neighbors, datasets
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

def cross_val_score_solution(clf, gene_exp, tissue_type, cv=5):
    # TODO: replace this implementation using your implementation using only 
    # builtin python or numpy data-structures and functions, 
    # and sklearn score function.
    # Function should return a single floating point accuracy 
    scores = cross_val_score(clf, gene_exp, tissue_type, cv=cv)
    return scores.mean()

n_neighbors = 15
clf = neighbors.KNeighborsClassifier(n_neighbors, weights='uniform')

gene_exp = pd.read_csv("gene_expr.csv", header=None).values
tissue_type = pd.read_csv("gene_labels.csv", header=None).values
gene_exp = np.transpose(gene_exp)
tissue_type = np.ravel(tissue_type)

# incorrect- testing on training set. Wrong!!!!!
clf.fit(gene_exp, tissue_type)
print("Wrong accuracy: %0.2f" % clf.score(gene_exp, tissue_type))

# we use an independent test set. Correct!!!!!!!!!
X_train, X_test, y_train, y_test = train_test_split(gene_exp, tissue_type, test_size=0.3, random_state=0)
clf.fit(X_train, y_train)
print("Independ. set accuracy: %0.2f" % clf.score(X_test, y_test))
      
# cv- also correct!!!!!!!
# TODO: your cross-validation function should return the mean accuracy
mean_accuracy = cross_val_score_solution(clf, gene_exp, tissue_type, cv=5)
print("CV accuracy: %0.2f" % (mean_accuracy))



Wrong accuracy: 0.72
Independ. set accuracy: 0.63
CV accuracy: 0.66


In [4]:
import numpy as np

# Useful numpy functions
# (see https://docs.scipy.org/doc/numpy/user/quickstart.html)

# create two numpy arrays
a = np.array([[1, 2], [3, 4]])
print(a)
print()
b = np.array([[5, 6]])
print(b)
print()

# now join a list of arrays
c = np.concatenate([a, b], axis=0)
print(c)
print()

# now split an array into a list
d = np.array_split(c, 3, axis=0)
print(d[0])
print(d[1])
print(d[2])

print()

# create an empty vector of length 5
z = np.zeros(5)
print(z)

[[1 2]
 [3 4]]

[[5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[1 2]]
[[3 4]]
[[5 6]]

[0. 0. 0. 0. 0.]
